### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by yuting9** [kriscross07/atom-gpp-compiler#1]
I may be doing this wrong, but I have done everything you recommended. I have installed MinGW from the site, and put D:\MinGW\bin\ in the path by doing the following:

My PC >> Properties >> Advanced System Settings >> Environment Variables >> Edit Path in system variables

I started Atom using the command prompt, and when I ran the standard "Hello World" code, I was shown the following screen:
![image](https://cloud.githubusercontent.com/assets/15150424/10532519/3dd9d99a-738d-11e5-9789-4b2ab0608a86.png)

Is there a way to fix these errors?

**Comment by yuting9** [comment]
I have fixed the problem by renaming the file as a single word.

**Comment by kriscross07** [comment]
I just updated the package to fix this error. Thank you for submitting this issue.
