### ISSUE TITLE
Linking Libraries

### ISSUE THREAD

**Issue by ENDev15** [kriscross07/atom-gpp-compiler#11]
I am currently working on a C++ project, that uses both the **GL**, **GLEW**, and **SDL2** libraries. How can I link these to this compiler? 

Atom is my favourite editor, and I'd rather not have to use Code Blocks long-term. 

Thanks!

**Comment by ENDev15** [comment]
It almost seems as though it works fine when I add `#include <GL/glew.h` to my C++ file after I have installed the libraries to my computer, but I'm not 100% sure so that's why I ask.

**Comment by ENDev15** [comment]
Sorry, I didn't mean to close and reopen the issue. Accidentally clicked the wrong button.

**Comment by kriscross07** [comment]
You can link the libraries with `#include <header.h>`, or ctrl clicking the header files in tree view, right clicking one of the files, and clicking `Compile and run`.
Also sorry for the late reply.

**Comment by ENDev15** [comment]
Thanks @kriscross07. That seemed to be the case when I originally tried but wasn't sure, because in programs such as Code::Blocks I have to manually link libraries in the project settings first.

Thanks again.
