### ISSUE TITLE
Don't recognize space on names os files and folders

### ISSUE THREAD

**Issue by matheustdo** [kriscross07/atom-gpp-compiler#112]
The compiler can't recognize space on names of files and folders, and shows: "is not recognized as an internal or external command, operable program or batch file".

**Comment by giuseppetrematerra** [comment]
Dump. Me too.
I tried to edit Line 403 `const command = `start "${info.name}" cmd /C "${gdb ? "gdb" : ""} ${file} ${gdb ? "" : "& echo. & pause"}`;`
in this way:
`const command = `start "${info.name}" cmd /C "${gdb ? "gdb" : ""} "${file}" ${gdb ? "" : "& echo. & pause"}`;`
but it doesn't work the same
