### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by spkane31** [kriscross07/atom-gpp-compiler#12]
'g++' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

I have g++ installed and on my path, however the package won't compile a simple output project.

C:\Users\Sean>\mingw\bin\gcc --version
gcc (GCC) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

C:\Users\Sean>\mingw\bin\g++ --version
g++ (GCC) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by kriscross07** [comment]
Are you sure C:\MinGW\bin is in your path environment variable? Open command prompt and type g++ --version (without prefixing it with \mingw\bin\) and if it outputs '"g++" is not recognized as an internal or external command.', then C:\MinGW\bin is not in your path environment variable.
To fix this, please refer to this article: 
http://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/.

Did this fix your issue?
