### ISSUE TITLE
'gcc' could not be spawned.

### ISSUE THREAD

**Issue by Godsgrav3** [kriscross07/atom-gpp-compiler#132]
When I try to launch this package I get the following error: 'gcc' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

I have installed mingw I have added the following folder: C:\MinGW\bin to the system PATH. I cannot launch gcc or g++ from cmd but I can launch mingw-get.

System reboot and launching atom with administrator privileges will not fix this issue.

**Comment by Godsgrav3** [comment]
I was able to fix this issue on my Windows 10 machine the following way.

1. download and install the package gpp-compiler(this package).
2. Download and install MinGW.
3. place <del>C:\MinGW\dir</del> C:\MinGW\bin in your system path.
4. Open mingw-get.exe (if not already).
5. click on "Basic Setup" on the left-hand side.
![screenshot_2](https://user-images.githubusercontent.com/1346388/30389911-9d7c4682-98b4-11e7-8017-50b5cbde0528.png)
6. Select all the packages.
![screenshot_3](https://user-images.githubusercontent.com/1346388/30391365-5d539e5c-98b9-11e7-9bbb-040bc2982a58.png)
7. on the top left-hand side click on "installation" and "apply changes", this operation will take about 15-20 minutes.

After following this, you should be able to use gcc and g++ in atom. To check if it's working launch CMD and enter "gcc --version" and "g++ --version" you should see this:
![screenshot_4](https://user-images.githubusercontent.com/1346388/30391814-1547c244-98bb-11e7-94f1-4114075fd289.png)

Changed the PATH variable to C:\MinGW\bin. Thank you @lenienthornet and @prabhatranjan for pointing this out. My apologies for the late change

**Comment by Zentacross** [comment]
Thanks buddy!

**Comment by iBraven** [comment]
Why I ger this " 'gcc' is not recognized as an internal or external command" on my terminal? 
Any ideea how to fix it?
![2017-12-06 1](https://user-images.githubusercontent.com/33104713/33672998-530c1464-dab4-11e7-9b59-30b1f81a91fc.png)
![2017-12-06 2](https://user-images.githubusercontent.com/33104713/33673002-54c75e80-dab4-11e7-8b65-fda1237e556d.png)

**Comment by Godsgrav3** [comment]
I see that you added C:\MinGW and not C:\MinGW\dir, change this and try again. After this restart your computer.

Also, make sure you change the "System variables" "PATH" and not "CM2015DIR".

**Comment by iBraven** [comment]
Thanks you!

**Comment by ghost** [comment]
I had the same issue and been trying to fix it for an hour when all I had to do was restart Atom :(

**Comment by samosucreations** [comment]
To save on some time, when installing MinGW only select the mingw32-base package and any other packages that you think you'll use (Obj-C, C++, etc)

**Comment by lenienthornet** [comment]
Hei @wsvdyk would you check out my problem aswell? #166 
I've tried sevral things. Im getting the error when trying to find it in cmd with gpp --version and g++ --version saying that its not an valid command or something. 

I've also changed the path to include \dir at the ending. Did not help. And when i entred the file MinGW, i could see that it did not include the dir-file as you referd to. 
Appriciating the help bro!

btw; the installation of the packages took aprox five minutes or so.

**Comment by lenienthornet** [comment]
I made it! I had to change away from \dir to \bin 
Thanks nonetheless

**Comment by prabhatranjan** [comment]
yes, C:\MinGW\bin should be added to system path

**Comment by yippiez** [comment]
hey i added mingw to my path and in cmd it works but in atom it doesen't i have the package ass well is till get the same error

**Comment by medabme** [comment]
i found many problems, so plz help me, how can i change the path?

**Comment by lenienthornet** [comment]
@medaboumessaad You found sevral problems? May you share them?
Here is atleast the the map by map;
"My Computer" > "Properties" > "Advanced" > "Environment Variables" > "Path"

**Comment by medabme** [comment]
@lenienthornet i found 2 path one in user variables and the other in system variables, which sould i choose?

**Comment by Godsgrav3** [comment]
Hi @medaboumessaad It has been some time that I last changed my PATH variables, but I think it doesn't matter unless you use multiple accounts. If you want to use MinGW system-wide (multiple accounts) use 'system variables', if you want it only to affect your account use the 'user variable for [username]'.

You said you have several problems? what are the others?

**Comment by medabme** [comment]
thank you guys, i solved the problem by adding C:\MinGW\bin to my system path

**Comment by Titoratus** [comment]
If you download `mingw` default installation path will be: `C:\Program Files (x86)\mingw-w64`.
Therefore I added `C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin` to my system path (not `C:\MinGW\bin`) and it's working!

**Comment by AionDev** [comment]
Watch this tutorial if you wanna see it as video : https://www.youtube.com/watch?v=zaokK25DITo. And restart Atom twice. Ensure Atom is closed using the Task Manager in windows. Atom has processes running in the background even after the atom window disappears. So those background process prevent a clean restart and that's why i needed to restart twice.

**Comment by ghost** [comment]
Please anybody can solve this problem

fs.js:157

**Comment by trescalaveras** [comment]
I added C:\MinGW\bin should be added to system path and User Variables, then I restart Atom and that's it, first I added it to System Variables path but nothing happens then I added it to User Variables and voila, it works, I can compile my program in C++, but I have another issue, where can I post it?
