### ISSUE TITLE
G++ could not be spawned but g++ is working and on path

### ISSUE THREAD

**Issue by AlanQuille** [kriscross07/atom-gpp-compiler#147]
I took great care to make sure MingW/bin is on the system path, g++ is working and I actually compiled my cpp file from the command prompt successfully.  I can prove this.

But it still says G++ could not be spawned. Do I have to configure atom to get it to work with g++? I'm confused.

**Comment by AdoUse** [comment]
i don't known sorry, that was the errore message, anyway try to configure atom to get it to work with g++

**Comment by AlanQuille** [comment]
I managed to get it working, thanks anyway :)

**Comment by Rebolledo20** [comment]
I installa the minGW and add it to path and doesnt work I need help please.

josel.rebo@gmail.com (Hangouts or email)
