### ISSUE TITLE
Set the package issue

### ISSUE THREAD

**Issue by iBraven** [kriscross07/atom-gpp-compiler#157]
My compiler doesn`t work. I installed MinGW and I added it to the PATH. I get the " 'gcc' could not be spawned"
![2017-12-06](https://user-images.githubusercontent.com/33104713/33672181-49e3b844-dab2-11e7-8ba1-38506cd9e36b.png)
![2017-12-06 1](https://user-images.githubusercontent.com/33104713/33672182-4a148780-dab2-11e7-9c0f-dc100edb7a02.png)

**Comment by mikechuck** [comment]
Hey @iBraven, I think the you have to add "C:\MinGW\bin" to your PATH. Not sure if that makes a difference, but it's worth a shot.

**Comment by turnipjs** [comment]
Have you restarted Atom since adding to your path?
