### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by lenienthornet** [kriscross07/atom-gpp-compiler#166]
Hey! Im strugling with compiling an c++ file on atom.

Getting this message; 
Uncaught Error: spawn g++ ENOENT
    at exports._errnoException (util.js:1022)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193)
    at onErrorNT (internal/child_process.js:359)
    at _combinedTickCallback (internal/process/next_tick.js:74)
    at process._tickCallback (internal/process/next_tick.js:98)

What i have done;
1. Installed krisscross07 gpp-compiler 3.0.7
2. Installed minGW
3. Checked all boxes and installed them.
4. Added path in the enviornment - c:\minGW

Then getting the errormessage saying: " 'g++' could not be spawned. Is it installed and on your path? if so please open an issue on the package spawning the process"

I've gone in to the CMD and asked: whre g++. Getting the answer: INFO: Could not find files for the given pattern(s).

thanks!

**Comment by lenienthornet** [comment]
I have made it. I had to change the path. Ended up with the following path: c:\minGW\bin

**Comment by Raj2032** [comment]
How did you change the path to c:\minGW\bin?

**Comment by lenienthornet** [comment]
Hey @Raj2032 ! Just follow the regular instructions given in the youtube-tutorials. Im not sitting on a windows-computer now, so i cant help you right now with finding the pathway, since i cant rememeber it. But nonetheless, after following the instructions, the only thing that did not work to me was their suggested path, i had to add \bin

**Comment by lenienthornet** [comment]
"My Computer" > "Properties" > "Advanced" > "Environment Variables" > "Path"

**Comment by Raj2032** [comment]
I did do that https://i.stack.imgur.com/9wgky.png

It still doesn't work. Could you please take a look at my issue please as I
am getting this weird error, thanks :)
https://github.com/kriscross07/atom-gpp-compiler/issues/170

**Comment by Raj2032** [comment]
Hey man I really need to know when I click on the download button in the
MinGW official page http://www.mingw.org do I get a 32 bit compiler or a 64
bit compiler, as I don't want to install a 32 bit compiler?

**Comment by lenienthornet** [comment]
Im not sure. I only use 64 bit, and it was not a issue for me at all.
