### ISSUE TITLE
advise: compile and run after program auto pause

### ISSUE THREAD

**Issue by netcan** [kriscross07/atom-gpp-compiler#19]

**Comment by kriscross07** [comment]
If you are using Linux, make your terminal XTerm, Konsole (if you are using the KDE desktop), or xfce4-term (if you are using the XFCE desktop) in gpp-compiler settings, which have hold command line option.

If you are using Windows, v2.3.0 added this functionality, so update to v2.3.0.

If you are using Mac, I don't have a Mac to test new features out so I would be unable to make changes without a pull request.

Does this fix your issue?

**Comment by netcan** [comment]
thanks a lot, I used windows and update it to solved.

**Comment by netcan** [comment]
![qq 20160602090522](https://cloud.githubusercontent.com/assets/11377070/15730694/5c8712c6-28a1-11e6-8e11-8904d2beecf1.png)
I found the new problems that it run could not be founded.
`child_process.exec(`start "${info.name}" cmd /C "${info.name}; & echo. & pause"`);`
I guess the running directory is not in the program directory.

**Comment by netcan** [comment]
I'm sorry, It works because I closed other files.

**Comment by kriscross07** [comment]
Whoops, you're right. The application isn't being run in the correct directory. Fixed in v2.3.1.

Thanks for reporting this bug, I should have tested it in Windows before publishing a new version.
