### ISSUE TITLE
'g++' could not be spawned.

### ISSUE THREAD

**Issue by bhavitvyamalik** [kriscross07/atom-gpp-compiler#20]
My c++ file is not getting compiled due to this. I checked the previous query in which you asked him to write g++ --version in cmd. I did the same and it returned me the version no. of it. Yet this file is not getting compiled in my system.
Thank you

**Comment by kriscross07** [comment]
Which operating system are you running?

In Atom, press `Ctrl + (Shfit / Alt) + I`, click Console and enter
```javascript
process.env.PATH
```
and reply with the output.

Try starting Atom from the command line by typing atom into `atom`. I don't know if this will work on Windows, though, so if it doesn't just ignore this.

In the cmd type `echo %PATH%`.

Try compiling with all other plugins disabled.

What is the output of
```javascript
require("child_process").spawn("g++", ["--version"]).stdout.on("data", (data) => {console.log(data.toString());});
```
in the Ctrl + (Shift / Alt) + I console?

**Comment by bhavitvyamalik** [comment]
I was using windows 10 .
I tried to compile it again it worked fine !
thank you :)
