### ISSUE TITLE
Problem launching compiled program

### ISSUE THREAD

**Issue by Kuroonehalf** [kriscross07/atom-gpp-compiler#21]
Hi. For some reason I can get my C programs to compile just fine (I've checked on the directory of the C file and the executable is created there correctly), but when it comes to running it's giving me an error, like so:
![helloworld 2](https://cloud.githubusercontent.com/assets/12227163/15967972/dbba892a-2f21-11e6-8f05-31f33992d063.png)

I believe the problem is the full path of the program is not being correctly piped into cmd, but I have no idea if that's actually the case, or why it's happening. 

This exact issue happens with another C compile&run package called gcc-make-run. I am on Windows8.1, in case it's relevant.

Help would be much appreciated.

**Comment by kriscross07** [comment]
What is the full path of the .cpp file?

**Comment by Kuroonehalf** [comment]
It's C:\Users\Kuro\Desktop\School\IA\2016\Test\helloworld.c

**Comment by kriscross07** [comment]
That's a C file, are you trying to compile C++?
To compile C++, press F5, to compile C, press F6.

**Comment by Kuroonehalf** [comment]
No sir, I'm trying to compile C. I've done from tree view > "Compile and run C", and doing it by the shortcut, it's still the same.

Also, as I said the compiling part works fine. On the file's directory the exe shows up, and running it manually I see that the expected output shows up on cmd.

It's launching that executable automatically after compiling that is the problem.

**Comment by kriscross07** [comment]
Which version of gpp-compiler are you running?

**Comment by Kuroonehalf** [comment]
Version 2.3.1

**Comment by kriscross07** [comment]
To aid in debugging, I added a debug branch.

- Go to [kriscross07/atom-gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler), click on branch > debug.
- Click on Clone or download > Download ZIP.
- Save and extract the ZIP.
- Open command prompt, cd into the extracted directory.
- Run `apm link`.

**Comment by Kuroonehalf** [comment]
I get the following error message:

Linking C:\Users\Kuro\.atom\packages\gpp-compiler to C:\Users\Kuro\Desktop\atom-gpp-compiler-debug failed: EEXIST, file already exists 'C:\Users\Kuro\Desktop\at
om-gpp-compiler-debug'

Am I supposed to extract it in a specific directory perhaps? :<

**Comment by kriscross07** [comment]
Odd, did you delete the gpp-compiler package first?
Maybe `apm link` doesn't work in Windows like it does on *nix.
Rename atom-gpp-compiler-debug to gpp-compiler and move it to C:\Users\Kuro\.atom\packages\ if apm link doesn't work.

**Comment by Kuroonehalf** [comment]
Kay, replaced all the files with the version on the packages folder.

I tried compiling&running the C file again, now I get an extra error box, like so:

![gpp-compiler](https://cloud.githubusercontent.com/assets/12227163/15972499/bc835130-2f36-11e6-9968-422d7fda9153.png)

**Comment by kriscross07** [comment]
That extra error box is because the debug branch tries to run the compiled program twice, using the new method and the old one.

What is the output in the Console tab of Ctrl + Alt + i?

**Comment by Kuroonehalf** [comment]
![helloworld c_ _cuserskurodesktopschoolia201](https://cloud.githubusercontent.com/assets/12227163/15972645/9ef05400-2f37-11e6-9444-d68075d714bb.png)

**Comment by kriscross07** [comment]
Open command prompt and enter this:
```batch
cd C:\Users\Kuro\Desktop\School\IA\2016\Test
helloworld
helloworld.exe
```
What is the output?

**Comment by Kuroonehalf** [comment]
![command_prompt 2](https://cloud.githubusercontent.com/assets/12227163/15972882/a91790b4-2f38-11e6-89e0-7620f2f69948.png)

**Comment by kriscross07** [comment]
What's the output of:
```batch
cd C:\Users\Kuro\Desktop\School\IA\2016\Test
start "helloworld" cmd /C "helloworld & echo. & pause"
```

**Comment by Kuroonehalf** [comment]
I get the input from the first screenshot I posted on the topic post.

**Comment by Kuroonehalf** [comment]
Output! I meant output, not input. :p

**Comment by kriscross07** [comment]
What's the output of:
```batch
cd C:\Users\Kuro\Desktop\School\IA\2016\Test
start "helloworld" "helloworld"
start "helloworld" "helloworld.exe"
start "helloworld" "cmd /C helloworld"
start "helloworld" "cmd /C helloworld.exe"
```
And what happens if you go into Atom settings, click on gpp-compiler's settings and change the File Extension option to `out`?

**Comment by Kuroonehalf** [comment]
The result to all those start commands is just a cmd window opening and immediately closing. I tried "cmd /C helloworld.exe & pause" too and I get the opening post output again.

And changing the file extension to out I get:
![program_manager](https://cloud.githubusercontent.com/assets/12227163/15973450/64d8eec2-2f3b-11e6-94ce-1c1a2bfe9571.png)

**Comment by kriscross07** [comment]
Using cmd's start builtin doesn't seem to spawn the command in the same directory.
What's the output of
```batch
cd C:\Users\Kuro\Desktop\School\IA\2016\Test
start "Title" cmd /C "type helloworld.c & pause"
start "Title" cmd /C "cd C:\ & type helloworld.c & pause"
```
Replace helloworld.c with the actual name of the file.

**Comment by Kuroonehalf** [comment]
Doing both of those I get a "The system cannot find the file specified." error.

I also tried `start "Title" cmd /C "type C:\Users\Kuro\Desktop\School\IA\2016\Test\helloworld.c & pause"`, for which I get the content of the C file (as in the actual code).

**Comment by kriscross07** [comment]
On my Windows 10 machine, the start command spawns cmd in the correct directory, and it doesn't seem to do that on yours so I'm going to get a Windows 8.1 virtual machine up and try to reproduce that error.

**Comment by Kuroonehalf** [comment]
Thank you. Apologies for the trouble. >.<

**Comment by kriscross07** [comment]
I am unable to reproduce even in Windows 8.
Have you tried disabling every plugin besides gpp-compiler and retrying?

**Comment by Kuroonehalf** [comment]
I just did and yeah, it's the same. :<

Though now I did some googling around and tried some stuff out, and found that this works:
`start cmd /C "%CD%\helloworld & echo. & pause"`

The %CD% correctly pulls the path of where the file is in. Is there perhaps a way to build this into the package, or a way for me to alter my version of it to work like this?

**Comment by kriscross07** [comment]
I already tried that, but figured out `start cmd /C "%CD%\helloworld & pause"` evaluates %CD% before running the command, so you're actually running `start cmd /C "C:\Users\Kuro\Desktop\School\IA\2016\Test\helloworld & pause"`.
That means `start cmd /C "cd C:\ & %CD%\helloworld & pause"` still runs the program even after cd'ing into your root, because %CD% is evaluated first.

Since I cannot reproduce the error you are having, tomorrow I will release an update that uses the full path to run the program (which is what I should have done in the first place).

**Comment by kriscross07** [comment]
Can you try out the new debug branch by following the steps in [this comment](https://github.com/kriscross07/atom-gpp-compiler/issues/21#issuecomment-225237520) and tell me if it works or not?

**Comment by Kuroonehalf** [comment]
It works properly now! Thanks!

**Comment by kriscross07** [comment]
I merged the debug branch to master and published a patch so you can safely delete the directory you extracted to ~/.atom/packages and download gpp-compiler from Atom's user interface.
