### ISSUE TITLE
'xfce4-terminal' could not be spawned. Is it installed and on your path?

### ISSUE THREAD

**Issue by akanshgulati** [kriscross07/atom-gpp-compiler#22]
I am seeing four options, Xterm, GNOME, Konsole and xfce4 under these terminals and I am using elementary OS. Could you please help regarding this.

**Comment by kriscross07** [comment]
I just added support for pantheon-terminal in v2.3.3, which is the default terminal in Pantheon (elementaryOS's default desktop environment).
You may upgrade to v2.3.3 to use pantheon-terminal, but I recommend using XTerm, which has a `--hold` option so the terminal doesn't instantly quit after the program exits.

To install XTerm run `sudo apt install xterm` in the terminal on any Debian-based Linux distro.

Does this fix your issue?

**Comment by akanshgulati** [comment]
Thanks for the help. It solved the issue and I have to install xterm for holding the screen.
