### ISSUE TITLE
Feature request: attach GDB debugger to program running process

### ISSUE THREAD

**Issue by fusion809** [kriscross07/atom-gpp-compiler#23]
Hi,

I would like to request that a new option (menu and keymap option) be added to this package to compile, run and attach the GDB debugger to the run process. 

Thanks for your time,
Brenton

**Comment by kriscross07** [comment]
Added in v3.0.0. To attach the debugger, press <kbd>F6</kbd> or right click the file in tree view and click `Compile and Debug`.
