### ISSUE TITLE
Can't compile in C++

### ISSUE THREAD

**Issue by MariusSMA** [kriscross07/atom-gpp-compiler#247]
Hello, I have a problem with the compiler in Atom for C++
![screenshot_20181201133941](https://user-images.githubusercontent.com/45511881/49327806-9cc27f00-f56e-11e8-9af0-f0feaabee291.png)

**Comment by MariusSMA** [comment]
I installed MinGW and changed the path, what I should do?

**Comment by astrolemonade** [comment]
I have the same problem

**Comment by astrolemonade** [comment]
Can you look into this issue, any solution ?

**Comment by cristicretu** [comment]
same problem here

**Comment by loeksnokes** [comment]
I had this problem but it is fixed now.  Windows 10.  When you change the path variable, firstly you must change the system version of path (which I had done anyway).  Secondly, the addition (e.g.), C:\MinGW should be at the end of the path on a new line in hte Windows interface describing the path.  You can do this by (in the correct window for path editing) adding a new line to the path at the bottom: not pre-pending in first line of path as I originally did following the instructions for installing MinGW on system (which also for some reason listed my inserted text in quotes I did not actually write).  Weh I re-edited path this way it seems to have fixed this issue: compile now runs with no error and Atom reports success.  Hope this helps.
