### ISSUE TITLE
Uncaught The "file" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by mod-john** [kriscross07/atom-gpp-compiler#259]
So in Atom I used the menu item "Add Project Folder", used the file manager to create a folder, "sentdex_go_tutor", then open. Now I created my first file using "New File" in right-click menu, "gotut.go", then I proceeded to enter this code:

```
package main

import "fmt"

func main() {
	fmt.Println("Welcome to Go!")
}

```

So I go ahead and save then I hit "F5" button to hopefully compile and run my code. This is where I get the error message as hopefully documented here. This is a pretty fresh install of Atom, novice user so not doing anything crazy and using an update to date and pretty fresh install of Arch Linux. So it's sad that right away there is a bug. I can compile and run golang code on the command prompt without a issue.

**Atom**: 1.34.0 x64
**Electron**: 3.1.3
**OS**: linux 4.20.6-arch1-1-ARCH
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught The "file" argument must be of type string. Received type undefined

```
At child_process.js:409

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type undefined
    at normalizeSpawnArguments (child_process.js:409:11)
    at Object.spawn (child_process.js:534:38)
    at compile (/packages/gpp-compiler/index.js:274:31)
    at compileFile (/packages/gpp-compiler/index.js:216:5)
    at /packages/gpp-compiler/index.js:23:11)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:384:43)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:617:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:408:22)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:110:34)
```

### Commands

```
     -2:23.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -2:23.5.0 editor:newline (input.hidden-input)
  2x -1:41.1.0 core:backspace (input.hidden-input)
     -1:39.2.0 autocomplete-plus:confirm (input.hidden-input)
     -1:39.2.0 snippets:expand (atom-text-editor.editor.enable-atom-ide-find-references.is-focused.autocomplete-active)
     -1:36.9.0 core:move-right (input.hidden-input)
     -1:35 core:move-left (input.hidden-input)
  6x -1:31.2.0 core:move-down (input.hidden-input)
     -1:13.7.0 autocomplete-plus:confirm (input.hidden-input)
     -1:10.3.0 core:move-left (input.hidden-input)
     -0:58.1.0 core:backspace (input.hidden-input)
     -0:57.7.0 core:move-left (input.hidden-input)
     -0:53.7.0 core:save (input.hidden-input)
     -0:41.1.0 atom-ide-terminal:new-terminal (div.highlights)
     -0:22.6.0 code-format:format-code (div.line)
     -0:12.9.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
go-debug 1.6.2 
go-plus 6.1.0 
go-signature-statusbar 1.2.3 
gpp-compiler 3.0.7 
linter 2.3.0 
linter-gcc 0.7.1 
linter-golinter 1.3.0 
linter-tidy 2.4.0 
platformio-ide-terminal 2.9.0 
```

**Comment by vakul-singh** [comment]
how did you solve this error?

**Comment by loganhutcheson** [comment]
How I solved this issue as a mac user:
1.) Installed XCode from appstore
2.) Made sure I had the g++/gpp compiler by writing 'which gcc' and 'which g++' into terminal.
3.) Save the file in atom with a name ending with .cpp! If the program name does not end in .cpp the compiler will not recognize the file.

**Comment by frogzxd** [comment]
How I solved it as a Windows user (this is universal probably):
Ctrl + comma -> Packages -> gpp-compiler -> Disable
Re-enable it if you want to run c++ programs again

**Comment by Barbone** [comment]
> How I solved it as a Windows user (this is universal probably):
> Ctrl + comma -> Packages -> gpp-compiler -> Disable
> Re-enable it if you want to run c++ programs again

Had the same problem while trying to run Python files on Linux. Yes, disabling gpp-compiler resolved the issue.

**Comment by notavacillator** [comment]
> How I solved it as a Windows user (this is universal probably):
> Ctrl + comma -> Packages -> gpp-compiler -> Disable
> Re-enable it if you want to run c++ programs again

Is this the only way? I mean it's frustrating because I need to make programs in Python and C++ simultaneously.

**Comment by ArnobMahmud** [comment]
python isn't running on atom. someone please guide me to fix it.

**Comment by Takitaa** [comment]
> How I solved this issue as a mac user:
> 1.) Installed XCode from appstore
> 2.) Made sure I had the g++/gpp compiler by writing 'which gcc' and 'which g++' into terminal.
> 3.) Save the file in atom with a name ending with .cpp! If the program name does not end in .cpp the compiler will not recognize the file.

BRILLIANT!!! renaming the file to NAME.cpp worked!! I can't believe it. PS. I knew I had Xcode and gcc... THANKS!

**Comment by allanjade** [comment]
Am not satisfied about the available comments.No one's comment worked for me.

**Comment by Roddess** [comment]
I'm am Mr india

**Comment by Mynkla** [comment]
> > How I solved it as a Windows user (this is universal probably):
> > Ctrl + comma -> Packages -> gpp-compiler -> Disable
> > Re-enable it if you want to run c++ programs again
> 
> Had the same problem while trying to run Python files on Linux. Yes, disabling gpp-compiler resolved the issue.

Thankyou it's work
