### ISSUE TITLE
g++:error:CreateProcess:No such file or directory

### ISSUE THREAD

**Issue by Dimri** [kriscross07/atom-gpp-compiler#26]
Whenever i try to compile my C++ program. It give error:

g++:error:CreateProcess:No such file or directory. 

Please help. Thank you

**Comment by kriscross07** [comment]
* open Atom
* press <kbd>Ctrl + ,</kbd>
* click on the settings for `gpp-compiler`
* enable the `Debug Mode` option.
* reload Atom with <kbd>Ctrl + Alt + r</kbd>
* press <kbd>Ctrl + Shift + I</kbd> (Linux) or <kbd>Ctrl + Alt + i</kbd> (Windows)
* click the `Console` tab
* try to compile your C++ program
* right click the console, and click `Save as...`
* reply with the contents of the file

**Comment by Dimri** [comment]
Window load time: 791ms
activate()
platform win32
![console](https://cloud.githubusercontent.com/assets/20702053/17275961/95ae0e28-5737-11e6-986a-7d50d0918c70.jpg)

/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
POST https://www.google-analytics.com/collect?t=event&ec=window&ea=ended&ev=2468…75718-5fad-4c93-a253-5f863225675c&an=atom&av=1.8.0&sr=1360x768&aiid=stable net::ERR_CONNECTION_REFUSED
POST https://www.google-analytics.com/collect?t=event&ec=window&ea=started&v=1&t…75718-5fad-4c93-a253-5f863225675c&an=atom&av=1.8.0&sr=1360x768&aiid=stable net::ERR_CONNECTION_REFUSED
POST https://www.google-analytics.com/collect?t=timing&utc=shell&utv=load&utt=93…75718-5fad-4c93-a253-5f863225675c&an=atom&av=1.8.0&sr=1360x768&aiid=stable net::ERR_CONNECTION_REFUSED
POST https://www.google-analytics.com/collect?t=timing&utc=core&utv=load&utt=791…75718-5fad-4c93-a253-5f863225675c&an=atom&av=1.8.0&sr=1360x768&aiid=stable net::ERR_CONNECTION_REFUSED
POST https://www.google-analytics.com/collect?t=event&ec=deprecation-v3&ea=jshin…75718-5fad-4c93-a253-5f863225675c&an=atom&av=1.8.0&sr=1360x768&aiid=stable net::ERR_CONNECTION_REFUSED
gpp-compiler:compile
getFileType() undefined
compileFile() C++ undefined
getFilePath()
getCommand() C++
getTmp() intro1
getArgs() ["A:\Programs\intro1.cpp"] C:\Users\HH\AppData\Local\Temp\intro1 C++ null
compiler args ["A:\Programs\intro1.cpp", "-o", "C:\Users\HH\AppData\Local\Temp\intro1"]
compile() g++ Object {root: "A:\", dir: "A:\Programs", base: "intro1.cpp", ext: ".cpp", name: "intro1"} ["A:\Programs\intro1.cpp", "-o", "C:\Users\HH\AppData\Local\Temp\intro1"] undefined
config Object {addCompilingErr: false, debug: true, gccOptions: "", gppOptions: "", runAfterCompile: true}
saving...
stderr g++: error: CreateProcess: No such file or directory

exit code 1

**Comment by Dimri** [comment]
![console](https://cloud.githubusercontent.com/assets/20702053/17276208/86096032-573f-11e6-9c55-882db3510699.jpg)

**Comment by kriscross07** [comment]
What happens if you enter

```batch
gcc A:\Programs\intro1.cpp -o C:\Users\HH\AppData\Local\Temp\intro1
gcc A:\Programs\intro1.cpp -o A:\Programs\intro1.exe
cd A:\Programs
gcc intro1.cpp -o intro1.exe
```

in the command prompt?

**Comment by Dimri** [comment]
![cmd](https://cloud.githubusercontent.com/assets/20702053/17361745/95301d06-598f-11e6-9778-6661725c6eb5.JPG)

**Comment by Dimri** [comment]
sorry for late reply

**Comment by kriscross07** [comment]
What happens when you enter

```batch
A:
cd Programs
g++ intro1.cpp -o intro1.exe
```

in the command prompt?

**Comment by Dimri** [comment]
same error
g++: error: CreateProcess : No such file or directory

**Comment by kriscross07** [comment]
Sorry for the month long reply, but I am unable to reproduce this issue so I cannot help.

**Comment by anirudha-ani** [comment]
I have also faced the same problem while setting up Atom for C++ on Window 10. But later I found out that my MinGW was copied from Codeblocks folder. Reinstalling the packages through official MinGW installer and adding the directory path (for my case C:\MinGW\bin) in

Advance System Settings>Environment Variables > Path

solved the problem for me.

**Comment by Ayemidotman** [comment]
please can you help me out, mine is gcc: error: create process: No such file directory

**Comment by Ayemidotman** [comment]
yes,,, i got the answer... change the gcc to g++

**Comment by Gowq** [comment]
Eu nao sei

**Comment by LeafFourth** [comment]
I have experienced this problem before. The root cause is an exe file was unziped failed with the size zero. I tried another unzip tool to solved it.

For the problem, to know how it happened is important:  
  CreateProcess is a API to create a process, so the error indicated that the image file used to create the process may not exist.

How to solve it: 
  Add "-v" flags to run gcc/g++ to compile and then, the verbose log shows. We can find which file not exists. If nothing goes wrong, we can just run the last command in the verbose log with flag  "-v"  to continue to check recursively.

**Comment by aharsi1298** [comment]
I have this same issue but I am running it in console. I considered LeafFourth's answer and checked the log with the -v option. The command(which I got directly from the gcc command) was `as -v -o C:\Users\<username>\AppData\Local\cc<random letters and numbers>.o C:\Users\<username>\AppData\Local\cc<random letters and numbers>.s`. What does it mean? Some more things just before that was:
`Compiler executable checksum: 72fdcf42c4c1c584c8e1347f320364c3` 
`COLLECT_GCC_OPTIONS='-o' './kernel.o' '-ffreestanding' '-v' '-mtune=generic' '-march=x86-64'`

P.S.:
The `<random letters and numbers>` are dynamic(they change every time)
