### ISSUE TITLE
using gpp compiler results in "'C:\Users\Name' is not recognized as an internal or external command, operable program or batch file." message

### ISSUE THREAD

**Issue by Janine85** [kriscross07/atom-gpp-compiler#260]
I'm having trouble with the compiler. After I hit F5 I get the above message. Any advice?

**Comment by ADepic** [comment]
Have you installed [mingw](http://www.mingw.org/) and [added it to your path](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/)

**Comment by MRDGH2821** [comment]
The actual problem is that the compiler gets file input as 
fgb g.c

not as -
"fgb g,c"

therefore such problem occurs.

Temp workaround - file name shouldn't have spaces

**Comment by DariushMazlumi** [comment]
@MRDGH2821 thank you, it worked!
but to add something to your answer, the entire path to the file should not have any space (not just the file's name).

**Comment by lakshits11** [comment]
Is there any way to resolve the issue??

**Comment by K-Pranay** [comment]
my file name had spaces and it worked fine for few days. i don't know what happend suddenly it showed this error. I even changed the name without spaces. it didn't work.
