### ISSUE TITLE
Uncaught TypeError: "file" argument must be a non-empty string 

### ISSUE THREAD

**Issue by trhgquan** [kriscross07/atom-gpp-compiler#270]
Okay guys, I don't have problems with the keystrokes but the right-click panel. Using gcc-compiler, right clicked on the items, hit "Compile and Run" and whoala! Nothing happened but a red alert showing "Uncaught TypeError: "file" argument must be a non-empty string".

![movie](https://user-images.githubusercontent.com/35959277/60889155-945bc080-a282-11e9-80dd-886b9607af58.gif)

How can I fix this problem?

Also I had commented on #246 but no response, so I post a new Issue. Please help me with this!

### **This error is far different from #246**

**Comment by polikuo** [comment]
Hi, I have the same problem on my windows machine.


It seems that **at line 403** in file **index.js** requires some fixing.


It looks like the "file" is parsed by various programs. (js, cmd, gdb...)


To solve the problem, I have made some tweaks.


I'm using _Atom 1.38.2_ on _Windows 10 64-bit_ host.


Here's the link to the patch file: [win32_filepath_patch.txt](https://github.com/kriscross07/atom-gpp-compiler/files/3402888/win32_filepath_patch.txt)

Simply put, replace
`start "${info.name}" cmd /C "${gdb ? "gdb" : ""} ${file} ${gdb ? "" : "& echo. & pause"}`
with
`start "${info.name}" cmd /C ${gdb ? "gdb \^\\\^\"" : "\"\""}${file}${gdb ? "\^\\\^\"" : "\" & echo. & pause\""}`
should do.

I'm taking "Hello World" as an example.


The original setting would generate:
F5: `start "Hello World" cmd /C " C:\Windows\Temp\Hello World & echo. & pause`
F6: `start "Hello World" cmd /C "gdb C:\Windows\Temp\Hello World`

The correct commands should be:
F5: `start "Hello World" cmd /C ""C:\Windows\Temp\Hello World" & echo. & pause"`
F6: `start "Hello World" cmd /C gdb ^\^"C:\Windows\Temp\Hello World^\^"`

Cheers ~~

**Comment by trhgquan** [comment]
@polikuo 

![ezgif-1-53692f648c2f](https://user-images.githubusercontent.com/35959277/61540147-45264480-aa67-11e9-9daf-9fda1eeee957.gif)

I've tried your solution, it recognised *.cpp file extension but not recognising *.CPP. Help me :(

**Comment by polikuo** [comment]
I'm afraid I couldn't solve your problem.

I've created 2 files for testing.

**Hello world.C**

#include <stdio.h>
int main(int argc, char const *argv[]) {
  printf("Hello world!\n");
  return 0;
}

**Hello world.CPP**

#include <iostream>
int main(int argc, char const *argv[]) {
  std::cout << "Hello world!" << '\n';
  return 0;
}

When I press F5/F6 everything works as expected.

It compiles and runs normally.

Perhaps you should try #159 instead.
