### ISSUE TITLE
show the compile info?

### ISSUE THREAD

**Issue by kokutoukiritsugu** [kriscross07/atom-gpp-compiler#29]
show in seprate cmd window?
like run step?

then we don't need compiling_error.txt option.

**Comment by kriscross07** [comment]
What exactly do you mean?

**Comment by kokutoukiritsugu** [comment]
If program compile with no error, it does't show any warning.
I wan't see all the warning.
I don't want only error.

![sp160822_122306](https://cloud.githubusercontent.com/assets/5471433/17843684/7ddef3ba-6863-11e6-95f4-456e7c3b1658.png)

**Comment by kriscross07** [comment]
Added in v3.0.5. You can now see compiler warnings.
