### ISSUE TITLE
Compiler error when compiling multiple files

### ISSUE THREAD

**Issue by JuanCtan02** [kriscross07/atom-gpp-compiler#3]
Hi,
I wrote "*.cpp -o File" into the settings so that when I compile, it will compile all the files in the directory, but instead it throws an error saying this:
C:\Users\JUANAN~1\AppData\Local\Temp\ccGEf6iK.o:C++_Test1.cpp:(.text+0x0): multiple definition of `BasicMathFunction()'
C:\Users\JUANAN~1\AppData\Local\Temp\cc7bT1s7.o:C++_Test1.cpp:(.text+0x0): first defined here
C:\Users\JUANAN~1\AppData\Local\Temp\ccGEf6iK.o:C++_Test1.cpp:(.text+0x10b): multiple definition of `DuplicateNumber(int)'
C:\Users\JUANAN~1\AppData\Local\Temp\cc7bT1s7.o:C++_Test1.cpp:(.text+0x10b): first defined here
C:\Users\JUANAN~1\AppData\Local\Temp\ccGEf6iK.o:C++_Test1.cpp:(.text+0x125): multiple definition of `main'
C:\Users\JUANAN~1\AppData\Local\Temp\cc7bT1s7.o:C++_Test1.cpp:(.text+0x125): first defined here
collect2.exe: error: ld returned 1 exit status

Is there another way to compile multiple files or a way to fix this error?
Thanks.

**Comment by PoVa** [comment]
Where did you write it? In g++ command line options?

**Comment by JuanCtan02** [comment]
Sorry for long response time, Ive been busy.
Yes, I wrote it in the g++ command line options in the package settings

**Comment by kriscross07** [comment]
Now you can compile multiple files by selecting them in tree view and right click `Compile and run`.
