### ISSUE TITLE
can give a option to change compiler?

### ISSUE THREAD

**Issue by kokutoukiritsugu** [kriscross07/atom-gpp-compiler#30]
or just give us all compile and run command.
then we can change it myself. 

like this:

c compiler:
gcc

c compiler options:
-Wall -std=c99

cpp...
cpp...

口 after compile pause.(run pause after compile finished.)
口 run after compile.

**Comment by kriscross07** [comment]
What compiler would you use other than GCC?

**Comment by kokutoukiritsugu** [comment]
clang.

**Comment by kriscross07** [comment]
Added in v3.0.5.

**Comment by tronganh29** [comment]
How do I add -lm to gcc compiler?
