### ISSUE TITLE
GNOME terminal annoying blue bar

### ISSUE THREAD

**Issue by zohaad** [kriscross07/atom-gpp-compiler#31]
I get an annoying blue bar on top of my terminal that says:

The child process exited normally with status 0.

How to remove this, it prevents me from seeing the first two lines of the output

**Comment by kriscross07** [comment]
As far as I know, you cannot make GNOME Terminal not show that bar. I recommend using XTerm for gpp-compiler instead. Go to gpp-compiler's settings and change the default terminal to XTerm, or something else.
