### ISSUE TITLE
No Compiling_Error.txt

### ISSUE THREAD

**Issue by ghost** [kriscross07/atom-gpp-compiler#320]
No .txt is being generated when running C++ code.

**Comment by kuroshojo** [comment]
I think the project has been dropped so any corrupted file wont be fixed try and compile it through terminal with command gcc FileName.c -o FileName(You just change the name in something different so you can separate them)

**Comment by ghost** [comment]
Aw, shame. Through terminal everything works fine, but I just wanted to know if the issue could be resolved. Thanks for the help anyway.
