### ISSUE TITLE
No linking options available

### ISSUE THREAD

**Issue by fould12** [kriscross07/atom-gpp-compiler#33]
When trying to include the library <GL/glut.h>, the attatched compiling_error is returned.
[compiling_error.txt](https://github.com/kriscross07/atom-gpp-compiler/files/432874/compiling_error.txt)

**Comment by kriscross07** [comment]
I don't understand the question. Which library are you trying to include? You may have to ctrl click the file in tree view along with your C/C++ file, right click, and click `Compile and run`.

**Comment by fould12** [comment]
Oh, sorry! When trying to include the "gl/glut.h" library, it gives the compiling error. I think the problem is I wasn't able to specify any linking options like I would with g++ in the terminal:
"g++ main.cpp -lfreeglut -lopengl32 -lglu32 -o release.exe".
C++ programs that use libraries that don't need the "-[optionname]" options can run fine, such as those that include "windows.h", but GLUT and OpenGL libraries don't work, and I think it's probably because I wasn't able to add "-lfreeglut -lopengl32 -lglu32" in the compiler options(links? linkers?).

**Comment by kriscross07** [comment]
You are able to specify linking options, or any compiler options by going into gpp-compiler's settings and changing the C Compiler/C++ Compiler command line options. This is a global change, though, and will compile every program with those flags. Is this what you wanted?

**Comment by fould12** [comment]
I think so; sorry, I'm used to using an IDE (code::blocks) that allows me to set custom linking options for each project. I never really used the compiler settings much, since it was all handled by the IDE.
I guess this is less of an issue, and more of a feature request (to set custom linking options for each project). You can delete(close?) this issue if you want.

**Comment by kriscross07** [comment]
I don't think I will add seperate options for each project to keep this package simple. If you need project specific options, use https://atom.io/packages/build.
