### ISSUE TITLE
G++ not being spawned 

### ISSUE THREAD

**Issue by Hunt092** [kriscross07/atom-gpp-compiler#341]
Even after adding it to the PATH and reinstalling mingGW twice now, I'm getting the same Error

**Comment by Subhadeep08** [comment]
try by restarting the editor

**Comment by zFireBlaze** [comment]
I have the same problem as you =(

**Comment by zFireBlaze** [comment]
Sei riuscito a risolvere? se si come potresti dirmelo?

**Comment by Hunt092** [comment]
sfortunatamente, non sono stato in grado di risolvere questo problema anche dopo una reinstallazione completa e tutto il resto, ma ho anche finito per non usare più atom, uso VSCode per la maggior parte delle mie cose e / o Codeblock per C ++ (in molto raro condizioni)

inoltre, ho usato Google Translate per questo non molto bene con l'italiano quindi, per favore, correggi da solo qualsiasi errore

**Comment by AnilDaal** [comment]
you can use to add path in local pc variable in path.Then restart  pc.
so try this
