### ISSUE TITLE
Uncaught TypeError: Callback must be a function. Received undefined

### ISSUE THREAD

**Issue by hakatu** [kriscross07/atom-gpp-compiler#352]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: Callback must be a function. Received undefined

```
At fs.js:142

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:142:9)
    at Object.writeFile (fs.js:1175:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

### Commands

```
     -0:17.2.0 gpp-compiler:tree-compile (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
```

//comments
I don't really understand, gcc and g++ working fine with cmd. Atom is not nightly as the previous error report. I tried to run with admin and without admin, same error.

**Comment by LeGarconAditya** [comment]
this only shows when your output window is already opened and you try to run the program

**Comment by parinay602** [comment]
> this only shows when your output window is already opened and you try to run the program

Saved my day
