### ISSUE TITLE
clang: error: no input files

### ISSUE THREAD

**Issue by jessyuan24** [kriscross07/atom-gpp-compiler#36]
clang: error: no input files.What's wrong?

**Comment by kriscross07** [comment]
* go into gpp-compiler's settings and enable the `Debug Mode` option
* open the developer tools and click on `Console`
* press F5 inside the editor
* right click on the console and click `Save as...`
* reply with the saved file's contents

**Comment by FrankyDBravo** [comment]
Hi same problem here:
[1520021016639.log](https://github.com/kriscross07/atom-gpp-compiler/files/1776422/1520021016639.log)
 That's what i get!
