### ISSUE TITLE
GNOME Terminal Not Working

### ISSUE THREAD

**Issue by Akshar-Patel** [kriscross07/atom-gpp-compiler#42]
Gnome Terminal should work in Ubuntu. But it opens and immediately closes in a second.

**Comment by kriscross07** [comment]
GNOME Terminal will close once the program is done executing because GNOME Terminal does not have a `-hold` option. Use XTerm instead, or go to Edit > Profile Preferences > Command > When command exits: > Hold the terminal open, but this will cause #31 to happen.

**Comment by Akshar-Patel** [comment]
Btw, Thanks for Great Plugin. :)

**Comment by julioNico** [comment]
> GNOME Terminal will close once the program is done executing because GNOME Terminal does not have a `-hold` option. Use XTerm instead, or go to Edit > Profile Preferences > Command > When command exits: > Hold the terminal open, but this will cause #31 to happen.

In my Linux Mint 19 Cinnamon, the GNOME Treminal close immediately, after running any program.
