### ISSUE TITLE
Listing your package on Pulsar

### ISSUE THREAD

**Issue by Daeraxa** [kriscross07/atom-gpp-compiler#426]
Hello, this is Daeraxa from the Pulsar Team.

[Pulsar](https://github.com/pulsar-edit/pulsar) is an actively developed fork of Atom and one of our major efforts is to preserve the ecosystem of [Community Packages](https://web.pulsar-edit.dev/) that were previously published on Atom.io

While we want to list every single package that existed on Atom's Package Repository, we wanted to respect the license of each package within and ensure to only list packages that either the author has agreed for us to or packages that have a license that specify that redistribution is okay.

That is exactly why we are contacting you today, it seems your package `atom-gpp-compiler` has a license that makes it hard for us to determine if we should be listing it for redistribution.

All that needs to happen for you as a package maintainer is for you to give authorization for us to list your package. Just reply to this issue either way and we will respect your wishes.

Otherwise within 3 weeks, if there is no response, we will assume the answer is no and remove your package from the Pulsar Package Registry.

And if you've missed the deadline we have and still want your package to be published, feel free to [republish to Pulsar](https://pulsar-edit.dev/docs/launch-manual/sections/core-hacking/#publishing).

Thanks a ton for your time, hope you have a great day!

**Comment by confused-Techie** [comment]
We appreciate any effort spent on this Issue. But as of now the 3 week period has passed.

That means that the package relating the the above issue will be deleted from our Database.

Again if you'd like to republish your package onto the Pulsar Package Registry we would be more than happy to have you.
And you can do so with the links provided above.

Thanks again, have a fantastic day!
