### ISSUE TITLE
internal/child_process.js:278

### ISSUE THREAD

**Issue by nilabja-bhattacharya** [kriscross07/atom-gpp-compiler#44]
![screenshot 19](https://cloud.githubusercontent.com/assets/17797160/18584482/b48450d4-7c2e-11e6-8abb-acbcfcee7577.png)
![screenshot 20](https://cloud.githubusercontent.com/assets/17797160/18584483/b488167e-7c2e-11e6-826c-ef96f26b3da6.png)

![screenshot 19](https://cloud.githubusercontent.com/assets/17797160/18584507/ccd394ce-7c2e-11e6-8c3a-dcabec6b17f6.png)
![screenshot 20](https://cloud.githubusercontent.com/assets/17797160/18584508/ccd484ce-7c2e-11e6-9d69-202d055d53ab.png)

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:278:26)
    at Object.exports.spawn (child_process.js:379:9)
    at compile (C:\Users\Neil.atom\packages\gpp-compiler\index.js:274:31)
    at tree-view-file.treeCompile (C:\Users\Neil.atom\packages\gpp-compiler\index.js:251:3)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Program Files (x86)\atom-windows\Atom\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Program Files (x86)\atom-windows\Atom\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Program Files (x86)\atom-windows\Atom\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Program Files (x86)\atom-windows\Atom\resources\app.asar\src\atom-environment.js:1115:28)
    at EventEmitter.outerCallback (C:\Program Files (x86)\atom-windows\Atom\resources\app.asar\src\application-delegate.js:342:25)
    at emitThree (events.js:110:13)
    at EventEmitter.emit (events.js:188:7)

**Comment by kriscross07** [comment]
Do you have the latest version of Atom?
Does disabling all other packages and restarting Atom fix this issue?
If not:
- go into gpp-compiler's settings and enable the `Debug Mode` option
- open the developer tools and click on `Console`
- press F5 on the C/C++ file
- right click on the console and click `Save as...`
- reply with the saved file's contents

**Comment by nilabja10201992** [comment]
[-1474132993174.txt](https://github.com/kriscross07/atom-gpp-compiler/files/478284/-1474132993174.txt)

After clicking F5, while in developer option and then compile and run, worked for my c++ files. I've provided the log of console after running my code. Thank You for helping me.. :+1:

**Comment by nilabja-bhattacharya** [comment]
[-1474133533706.txt](https://github.com/kriscross07/atom-gpp-compiler/files/478289/-1474133533706.txt)

My console log

**Comment by kriscross07** [comment]
Either Atom changed their API, or you are using a package that is changing the file type to `C++14`. Have you tried disabling all other plugins? Which version of Atom do you have?

**Comment by nilabja-bhattacharya** [comment]
I'm using Atom 1.10.2. 
Yes, I'm using cpp14 package, should I disable it?
Sometimes compile and run works, sometimes it doesn't.
I'm facing this problem since I installed, packages-
1. language-cpp14 and 2.linter-gcc

Previously I thought the root cause was linter-gcc, because disabling linter-gcc, wasn't throwing bad agrument, but I faced problem again later though I had my linter-gcc disabled.

Thank You Sir for helping me.. 👍

**Comment by trent0bri4n** [comment]
Hi!, I was trying to use Atom to compile a simple "hello world" program just to see how it works but It gives me back this error:

> internal/child_process.js:278 
> TypeError: Bad argument
>     at TypeError (native)
>     at ChildProcess.spawn (internal/child_process.js:278:26)
>     at Object.exports.spawn (child_process.js:384:9)
>     at compile (/Users/gourias/.atom/packages/gpp-compiler/index.js:274:31)
>     at compileFile (/Users/gourias/.atom/packages/gpp-compiler/index.js:216:5)
>     at atom-text-editor.gpp-compiler:compile (/Users/gourias/.atom/packages/gpp-compiler/index.js:23:11)
>     at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
>     at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
>     at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:584:16)
>     at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:379:22)
>     at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
>     at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)

I don't have any other community packages installed (no language-cpp14 or others - only gpp-compiler)

I'm running Atom on Mac OSX, and I've alredy installed "XCode Command Line Tools"

Any advise?
