### ISSUE TITLE
Not compiling.

### ISSUE THREAD

**Issue by Hisamera** [kriscross07/atom-gpp-compiler#6]
Dunno what you were trying to do but, {esc(["g++", info.base, "-o", info.name]) + ...} creates ('g++' 'something.cpp' '-o' 'something.exe' ...) instead of (g++ something.cpp -o something.exe ...) i'll advise to modify it to just {"g++ " + info.base + " -o " + info.name + ...} so that this will be avoided, because i don't know how on the other OSs but on windows it is now broken.

**Comment by kriscross07** [comment]
This issue should be fixed in version 1.2.2.
Please tell me if this update fixes your problem.

**Comment by Hisamera** [comment]
Fixed.
