### ISSUE TITLE
'g++' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

### ISSUE THREAD

**Issue by conorlawton** [kriscross07/atom-gpp-compiler#64]
Win10 64bit 
C:\MinGW\bin
![image](https://cloud.githubusercontent.com/assets/7032300/21305338/f57271f6-c5c2-11e6-8a5e-10f1f5c75fe0.png)
I've no idea why this is happening and it seems to be a different problem for everyone,
C:\>g++ --version
'g++' is not recognized as an internal or external command,
operable program or batch file.

**Comment by KiranAWolf** [comment]
<img width="943" alt="cinatom" src="https://cloud.githubusercontent.com/assets/19198057/21380055/6b2267ea-c720-11e6-9c2b-f0a51ffb0c61.PNG">

Getting the same issue on my Win 10 laptop. Turbo C++ is said to be the best IDE for C but it is a pain to use on Win 10, so I wanted to try Atom for C, but getting the error message when I compile and run the program. It compiles and runs on Turbo C++ but not on Atom.

**Comment by Sayan-Roy** [comment]
@Krn777 , Turbo C++ is the best IDE...Are you kidding me? Try CodeBlocks .
Now,coming to the issue, @1NAX2 
Firstly,check if C:\MInGW\bin is in your path environment variable. 
Secondly,after doing this try to close and reopen the Atom as the user(i ran it as an administrator) which has all (write,read,execute) permissions to the .c file .Your .c file might be read only.Check that first.It worked for me.
I might be wrong but what i did was this- i kept the c files in D drive and MinGW in C drive and then Atom compiles & runs it perfectly.Only when I kept the C files in C drive ,I had to run Atom as an administrator to compile and run my C file.

**Comment by procmixin** [comment]
Man. Took me so long and the only thing needed was to restart Atom. I completely forgot that I changed the Path variables after I had open Atom. :/

**Comment by panjiara** [comment]
Thanks! It started Working.

**Comment by PavanClo** [comment]
thank you bro it started to work

**Comment by meaturner** [comment]
How did you guys get it to start working? I am still having the same problem

**Comment by mdsharifulhaque** [comment]
Just restart the atom. This should be the fix.

**Comment by pprathameshmore** [comment]
@Sayan-Roy It worked for me. Thank you!

**Comment by ujjavalsinha** [comment]
Its not working ffor me

**Comment by hyp3r5pace** [comment]
Not working for me either....still it is not spawning

**Comment by Urban158** [comment]
Same here.  How do you restart Atom?

**Comment by Urban158** [comment]
New Error Message:
C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/bin/ld.exe: final link failed: No space left on device
collect2.exe: error: ld returned 1 exit status

**Comment by prasaddkadam** [comment]
I restarted the Atom but having the same Issue.
checked on Command Prompt for "g++ --version" and it says not recognized as an internal or external command.

EDIT: Okay, it was pretty simple. Just restart your pc and the Environment variables will be implemented, 
         Then everything will work fine.
         JUST RESTART THE PC (worked in my Case).

**Comment by SarvasvX** [comment]
I restarted atom as well as my pc... Still not working...plz help someone...
P.S. : the c:\mingw\bin has been set in path of environment variables.

**Comment by Godcreatebugs** [comment]
@sarvasvX I think the fix is that you should actually set environment variable for MinGW if that is your compiler. I restarted atom and PC but it didn't work for me. So, I tried to change minGW path variable and it works flawlessly now.

**Comment by Mandraulic** [comment]
Hey I got an issue setting up compilers for Cpp was wondering if I could try and get some help in here, I am also a Windows user:

This might be me though having no experience working on a project in an IDE before:

g++: error: /mnt/d/Coding/Cpp/helloworld.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
The IDE says CCLS Language for C/C++ unable to start is this something I would download  and install?

I have set up the pathing for g++ already and can verify it is recognized in my CMD prompt.

**Comment by utkzas** [comment]
when i press F5, nothing happens. :-(

**Comment by Viraj-M** [comment]
Tks worked man

**Comment by Revanthrockie** [comment]
Remember to restart atom after your done with changing the path location.
That will fix your problem for sure.

**Comment by conorlawton** [comment]
Issue is stale and appears to largely result from end user misconfiguration.
