### ISSUE TITLE
Compiling multiple files?

### ISSUE THREAD

**Issue by vinothbabu** [kriscross07/atom-gpp-compiler#7]
How would you compile multiple files using this plugin? A documentation or link might be helpful?

`/tmp/ccfoKnIs.o: In function main':<br>test.cpp:(.text+0x19): undefined reference toadd(int, int)'
test.cpp:(.text+0x66): undefined reference to add(int, int, int)'<br>test.cpp:(.text+0xaf): undefined reference totest(bool)'
test.cpp:(.text+0xec): undefined reference to `test(double)'
collect2: error: ld returned 1 exit status`

I get the above error, which states about the linking problem. I tried selecting the two files and clicked on compile and run, but no luck.

**Comment by kriscross07** [comment]
Can you include the file at the top of test.cpp with `#include "otherFile.cpp"` or `#include "otherFile.h"`?

**Comment by vinothbabu** [comment]
I tried including the header file, but it seems to throw the same error... 

`/tmp/ccaBYY9Q.o: In function main':<br>test.cpp:(.text+0x19): undefined reference toadd(int, int)'
test.cpp:(.text+0x66): undefined reference to add(int, int, int)'<br>test.cpp:(.text+0xaf): undefined reference totest(bool)'
test.cpp:(.text+0xec): undefined reference to `test(double)'
collect2: error: ld returned 1 exit status`

When i enter into command line and execute g++ test.cpp functions.cpp it works fine....

**Comment by kriscross07** [comment]
The new version of atom-gpp-compiler just released should allow you to compile multiple files by selecting the files you want to compile in tree view, right click, and click `Compile and run`.

**Comment by TijmenUU** [comment]
Using Atom 1.19.4 in combination with gpp-compiler 3.0.7 package still produces the same result mentioned by vinothbabu for me. Likewise, using the g++ CLI works fine here too. 

My platform is Windows 10 x64 1703 and g++ (GCC) version 5.3.0 is installed.

Any ideas?

**Comment by KristianKorsgaard** [comment]
I'm also having difficulties compiling multiple files, with package 3.0.7, running ubuntu 16.04. g++ CLI works fine.

EDIT: After more than an hour troubleshooting (and of course a few minutes after posting this) I finally got it working. Here's what to do, and what not to do:

**DON'T** right click on the file _name_, where a larger menu will appear if other plug-ins are installed, when wanting to press "Compile and Run"
![image](https://user-images.githubusercontent.com/5777710/30218403-44acee0c-94b9-11e7-8481-f6f7694bfee4.png)

**DO** right click on the blank space right beside the file name. Here a smaller menu will appear and you can press the "Compile and Run" or other commands without linking problems.
![image](https://user-images.githubusercontent.com/5777710/30218448-587a6914-94b9-11e7-9dbf-1bf92abd7f3c.png)

**Comment by TijmenUU** [comment]
Yeah, just like with deleting multiple files, using the context menu restricts selection to whatever you're right clicking. Seems to be a bug with Atom.io itself.

**Comment by anmol281** [comment]
@KristianKorsgaard i have tried but it is not working...

i am trying to use class declaration using (.h) and (.cpp) declaration.....

**Comment by aleksaa01** [comment]
Issue for me was that the path to those files contained a space character, and because of that it couldn't compile.
Error:
`'E:\C++_Projects\C++' is not recognized as an internal or external command,
operable program or batch file.`

And the path to those files was:
"E:\C++_Projects\C++ Example\example.cpp"
and
"E:\C++_Projects\C++ Example\example2.cpp"

Renaming "C++ Example" folder to "C++_Example", solved the problem...
