### ISSUE TITLE
[LINUX] 'xterm' could not be spawned

### ISSUE THREAD

**Issue by ghost** [kriscross07/atom-gpp-compiler#78]
I am using Elementary OS loki(Ubuntu 16.04). When I press f5, if there is error, it notifies, but otherwise it simply does not open the terminal and shows the following error:
'xterm' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

**Comment by artmkoo** [comment]
I find working solution in topick bellow (for me work correct): https://github.com/kriscross07/atom-gpp-compiler/issues/122
