### ISSUE TITLE
Uncaught TypeError: Incorrect value of args option

### ISSUE THREAD

**Issue by ASBaumgarten** [kriscross07/atom-gpp-compiler#9]
Enter steps to reproduce below:  1. ... 2. ... **Atom Version**: 1.5.3 **System**: Mac OS X 10.11.3 **Thrown From**:  gpp-compiler  https://github.com/kriscross07/atom-gpp-compiler  package, v2.0.1 ### Stack Trace Uncaught TypeError: Incorrect value of args option     At child_process.js:312 TypeError: Incorrect value of args option at normalizeSpawnArguments  child_process.js:312:11  at Object.exports.spawn  child_process.js:345:38  at ChildProcess. anonymous>  /Users/Alexander/.atom/packages/gpp-compiler/index.js:86:20  at emitTwo  events.js:87:13  at ChildProcess.emit  events.js:172:7  at maybeClose  internal/child_process.js:817:16  at Socket. anonymous>  internal/child_process.js:319:11  at emitOne  events.js:77:13  at Socket.emit  events.js:169:7  at Pipe._onclose  net.js:469:12      ### Commands     -4:26.9.0 gpp-compiler:f5Compile  atom-text-editor.editor.is-focused  2x -2:32.4.0 editor:newline  atom-text-editor.editor.is-focused  -2:27.8.0 autocomplete-plus:CONFIRM  atom-text-editor.editor.is-focused.autocomplete-active  -2:26.8.0 snippets:next-tab-stop  atom-text-editor.editor.is-focused  -2:26.8.0 snippets:expand  atom-text-editor.editor.is-focused  -2:26.8.0 editor:indent  atom-text-editor.editor.is-focused  -2:26.3.0 core:backspace  atom-text-editor.editor.is-focused  -2:24.7.0 autocomplete-plus:CONFIRM  atom-text-editor.editor.is-focused.autocomplete-active  6x -2:20.3.0 core:backspace  atom-text-editor.editor.is-focused  2x -2:11.6.0 autocomplete-plus:CONFIRM  atom-text-editor.editor.is-focused.autocomplete-active  2x -2:03.2.0 core:backspace  atom-text-editor.editor.is-focused  -1:55.1.0 autocomplete-plus:CONFIRM  atom-text-editor.editor.is-focused.autocomplete-active  -1:50.6.0 core:save  atom-text-editor.editor.is-focused  2x -1:48.5.0 gpp-compiler:f5Compile  atom-text-editor.editor.is-focused  -0:19.7.0 settings-view:check-for-package-updates  atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui  -0:01.5.0 gpp-compiler:f5Compile  atom-text-editor.editor.is-focused      ### Config    json { core : { disabledPackages :   dash , linter-pylint , autocomplete-paths   }, gpp-compiler : { gppOptions : -lncurses -std=c 11 } }     ### Installed Packages    coffee # User atom-beautify, v0.28.22 autocomplete-python, v1.6.1 coffee-compile, v0.21.1 debugger, v0.0.1 file-icons, v1.6.14 gpp-compiler, v2.0.1 language-lua, v0.9.4 linter-clang, v3.4.4 minimap, v4.19.0 minimap-git-diff, v4.1.8 pdf-view, v0.39.0 sync-settings, v0.6.0 # Dev No dev packages

**Comment by kriscross07** [comment]
The 2.0.1 release of the package should fix this error.
Please reply if updating fixed the error.

**Comment by ASBaumgarten** [comment]
Update fixed it. Thanks.
